### ISSUE TITLE
Do I really need all the materialize source just to display the loader?

### ISSUE THREAD

**Issue by sebastialonso** [leftstick/splash-screen#1]
I think it's a waste to load all the Materialize components when I'm just looking for the loader.

How could just get the styles and the required js code?

**Comment by leftstick** [comment]
Which part you think is too much?  The minified Js file is only 2KB, and CSS is a little larger 23KB. Or you want a custom build which only contains the preferred theme?

**Comment by sebastialonso** [comment]
I think it would a great idea if you allowed only to get certain part of the Materialize library. 
It's only 2KB yes, but I get a lot of things that I'm not going to use: calendar, toolitps to name a few.

Something like only the necessary to use the loader and the splash.

Great job anyway!

**Comment by leftstick** [comment]
Oh i see, you may have misunderstood with the demo page. http://leftstick.github.io/splash-screen/ only demonstrate each theme in `splash-screen` looks like. You don't need install any part of [Materialize Components](http://materializecss.com/). 

For using `splash-screen`'s library, just three or four lines of code, super easy! Check the [README](https://github.com/leftstick/splash-screen/blob/master/README.md) for more information
