### ISSUE TITLE
Is "destory" a typo?

### ISSUE THREAD

**Issue by ghost** [leftstick/splash-screen#2]
In the old version, it's `Splash.destroy()`.
After upgrade to the latest version (on the master tree), all usage become `Splash.destory()`.
It should be "destroy", doesn't it?

**Comment by leftstick** [comment]
Yes, it was a typo. Thanks for pointing this issue.

**Comment by ghost** [comment]
You forgot `README.md` ...

**Comment by leftstick** [comment]
@BinotaLIU  updated, thanks
