### ISSUE TITLE
Multiple Splash instances support

### ISSUE THREAD

**Issue by ghost** [leftstick/splash-screen#3]
Execute `Splash.enable` multiple times will create multiple instances on the DOM as we expected.
But, when execute `Splash.destroy`, all instances will be destroy, this is the unexpected result.

[I have implement this feature in the old version (3.0.1)](https://github.com/BinotaLIU/splash-screen/commit/fb40c72b3487533989e4aabc47e58451a0db3550), can you do the same thing in the latest version?

**Comment by leftstick** [comment]
Why do you need to create multiple `slpash`, Can you explain what scenario you are running in?

**Comment by ghost** [comment]
I have multiple tables on the same page, which data is loaded by ajax.
Every tables request their data separately, and each one will create their own Splash instance by running `Splash.enable`.
In this case, one table loaded, it will execute `Splash.destroy()`, and this cause all Splash instance been destroyed. This is an unexpected result since the other tables have not been loaded yet.

**Comment by leftstick** [comment]
OK, base on that, i suggest you to choose a spinner plugin instead(add loading animation for each individual table).  

The `splash` was designed as a whole viewport cover, the idea was powered by mobile splash(before the app is actually launched)
